import type { PageNode } from '@/types/crawler'

export const MOCK_PAGES: PageNode[] = [
  {
    id: 'root',
    url: 'https://example.com',
    path: '/',
    title: 'Example Domain — Home',
    depth: 0,
    statusCode: 200,
    childCount: 5,
    parentId: null,
    internalLinks: ['/about', '/pricing', '/blog', '/docs', '/contact'],
    externalLinks: ['https://iana.org/domains/example'],
    canonical: 'https://example.com',
    isExternal: false,
  },
  {
    id: 'about',
    url: 'https://example.com/about',
    path: '/about',
    title: 'About Us — Example',
    depth: 1,
    statusCode: 200,
    childCount: 0,
    parentId: 'root',
    internalLinks: ['/', '/contact'],
    externalLinks: [],
    canonical: 'https://example.com/about',
    isExternal: false,
  },
  {
    id: 'pricing',
    url: 'https://example.com/pricing',
    path: '/pricing',
    title: 'Pricing — Example',
    depth: 1,
    statusCode: 200,
    childCount: 0,
    parentId: 'root',
    internalLinks: ['/', '/contact', '/docs'],
    externalLinks: [],
    canonical: 'https://example.com/pricing',
    isExternal: false,
  },
  {
    id: 'blog',
    url: 'https://example.com/blog',
    path: '/blog',
    title: 'Blog — Example',
    depth: 1,
    statusCode: 200,
    childCount: 1,
    parentId: 'root',
    internalLinks: ['/', '/blog/how-it-works'],
    externalLinks: [],
    canonical: 'https://example.com/blog',
    isExternal: false,
  },
  {
    id: 'blog-how-it-works',
    url: 'https://example.com/blog/how-it-works',
    path: '/blog/how-it-works',
    title: 'How It Works — Example Blog',
    depth: 2,
    statusCode: 200,
    childCount: 0,
    parentId: 'blog',
    internalLinks: ['/blog', '/docs'],
    externalLinks: ['https://github.com/example'],
    canonical: 'https://example.com/blog/how-it-works',
    isExternal: false,
  },
  {
    id: 'docs',
    url: 'https://example.com/docs',
    path: '/docs',
    title: 'Documentation — Example',
    depth: 1,
    statusCode: 200,
    childCount: 0,
    parentId: 'root',
    internalLinks: ['/', '/pricing', '/blog'],
    externalLinks: ['https://github.com/example'],
    canonical: 'https://example.com/docs',
    isExternal: false,
  },
  {
    id: 'contact',
    url: 'https://example.com/contact',
    path: '/contact',
    title: 'Contact — Example',
    depth: 1,
    statusCode: 200,
    childCount: 0,
    parentId: 'root',
    internalLinks: ['/about', '/'],
    externalLinks: [],
    canonical: 'https://example.com/contact',
    isExternal: false,
  },
]

export const DEFAULT_CRAWL_OPTIONS = {
  url: '',
  maxDepth: 3,
  maxPages: 100,
  respectRobots: true,
  includeExternal: false,
}
