import type { PageNode } from '@/types/crawler'

function getDomain(url: string): string {
  try {
    return new URL(url).hostname.replace(/\./g, '-')
  } catch {
    return 'site'
  }
}

function getTimestamp(): string {
  return new Date().toISOString().slice(0, 19).replace(/[T:]/g, '-')
}

export function formatAsTxt(pages: PageNode[]): string {
  const sorted = [...pages].sort((a, b) => a.depth - b.depth || a.path.localeCompare(b.path))
  return sorted.map((p) => p.url).join('\n')
}

export function formatAsCsv(pages: PageNode[]): string {
  const header = 'url,path,depth,status_code,child_count,internal_links,external_links'
  const rows = pages.map((p) =>
    [
      `"${p.url}"`,
      `"${p.path}"`,
      p.depth,
      p.statusCode ?? '',
      p.childCount,
      p.internalLinks.length,
      p.externalLinks.length,
    ].join(',')
  )
  return [header, ...rows].join('\n')
}

export function formatAsJson(pages: PageNode[], rootUrl: string): string {
  return JSON.stringify(
    {
      metadata: {
        root_url: rootUrl,
        total_pages: pages.length,
        crawled_at: new Date().toISOString(),
        generated_by: 'CrawlMap',
      },
      pages: pages.map((p) => ({
        id: p.id,
        url: p.url,
        path: p.path,
        title: p.title,
        depth: p.depth,
        status_code: p.statusCode,
        child_count: p.childCount,
        parent_id: p.parentId,
        internal_links: p.internalLinks,
        external_links: p.externalLinks,
        canonical: p.canonical,
      })),
    },
    null,
    2
  )
}

export function formatAsXml(pages: PageNode[], rootUrl: string): string {
  const urls = pages
    .map(
      (p) =>
        `  <url>\n    <loc>${escapeXml(p.url)}</loc>\n    <depth>${p.depth}</depth>\n    <title>${escapeXml(p.title)}</title>\n  </url>`
    )
    .join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:crawlmap="https://crawlmap.dev/schema">
  <!-- Generated by CrawlMap | Root: ${escapeXml(rootUrl)} -->
${urls}
</urlset>`
}

export function formatAsMarkdown(pages: PageNode[], rootUrl: string): string {
  const lines: string[] = [
    `# Site Map: ${rootUrl}`,
    ``,
    `> Generated by [CrawlMap](https://crawlmap.dev) on ${new Date().toLocaleDateString()}`,
    `> Total pages: ${pages.length}`,
    ``,
    `## Pages`,
    ``,
  ]

  const byDepth = new Map<number, PageNode[]>()
  for (const p of pages) {
    if (!byDepth.has(p.depth)) byDepth.set(p.depth, [])
    byDepth.get(p.depth)!.push(p)
  }

  const indent = (depth: number) => '  '.repeat(depth)
  const sorted = [...pages].sort((a, b) => a.depth - b.depth || a.path.localeCompare(b.path))

  for (const p of sorted) {
    lines.push(`${indent(p.depth)}- [${p.path}](${p.url}) — ${p.title}`)
  }

  lines.push('', '## Raw URLs', '')
  for (const p of sorted) {
    lines.push(p.url)
  }

  return lines.join('\n')
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function getFilename(format: string, rootUrl: string): string {
  return `crawlmap-${getDomain(rootUrl)}-${getTimestamp()}.${format}`
}
